### ISSUE TITLE
does not work

### ISSUE THREAD

**Issue by kukac7** [PanMan/WP-JSON-API-ACF#9]
Hi,

Plugin.php copy the contents of the functions.php file.
If a post or page field I do not appear in the JSON output.

Advanced Custom Fields 4.4.1
WP REST API 1.1.1

What could be the problem?

**Comment by PanManAms** [comment]
I have no idea, but I would install it as a plugin, not copy the code.
What does work, what doesn't?

**Comment by kukac7** [comment]
@PanMan thank you for your reply! it seems the problem was that it was not the product number you specified in the ACF. but I test more.

**Comment by denitto** [comment]
hey @panmanams:  this worked fine until I updated to the current WP-API version (1.2.1).  Have you tested with the new version?
